### ISSUE TITLE
trans incorrect

### ISSUE THREAD

**Issue by Luceos** [sijad/flarum-ext-pages#1]
If there are no pages yet, the message shows an incorrect singular form:

```
It looks like there are no page here.
```

**Comment by sijad** [comment]
What should it be instead? *Pages*

**Comment by Luceos** [comment]
Yes either:

> It looks like there are no pages here.

Or:

> It look like there is no page here.

But the first is best.

**Comment by Luceos** [comment]
Cool, great work @sijad Sajjad ;)

**Comment by sijad** [comment]
thanks
