### ISSUE TITLE
Break line everywhere?

### ISSUE THREAD

**Issue by r0v** [sijad/flarum-ext-pages#10]
Hi!
When I add html some element I have a lot of `<br>` separated after and before this element.
It is very annoying. For example I add `<style>` tag with style and I have `<br><style></style><br>` ???
Obviously I can add css/less in flarum custom style but this example illustrate the problem with br.

PS. Sory for my english..

**Comment by sijad** [comment]
this should be fixed in master, can you please install `dev-master` version via composer and test again?

**Comment by r0v** [comment]
Yeah, now it's ok. After add dev-master branch works ;)  Thanks.

**Comment by sijad** [comment]
thanks for letting us know.
