### ISSUE TITLE
Hidden / show page feature

### ISSUE THREAD

**Issue by r0v** [sijad/flarum-ext-pages#11]
Hi! I have a new idea - I thinking what should have a page extension -> hide/show system.
Sometimes I must hide(deactive) one page without delete it so as to be invisible to the public (and vice versa).

This is not bad, and relatively simply to implementation. 
But this is only my suggestion.

Sry for bad my english.

**Comment by sijad** [comment]
draft feature do exactly same thing, admins also can see draft Preview.
